"""Data cleaning stage: whitespace trimming, unicode cleanup, and NULL standardization."""

from __future__ import annotations

import pandas as pd

# Null string placeholders commonly generated by POS systems
NULL_STRINGS = {"", "null", "none", "n/a", "na", "nan", "undefined", "<null>", "nil"}


def clean_dataframe(df: pd.DataFrame) -> pd.DataFrame:
    """Clean string columns by trimming whitespace, stripping non-printable characters, and standardizing NULLs.

    Args:
        df: Input DataFrame to clean.

    Returns:
        Cleaned Pandas DataFrame.
    """
    cleaned_df = df.copy()

    for col in cleaned_df.columns:
        if cleaned_df[col].dtype == "object" or isinstance(cleaned_df[col].dtype, pd.StringDtype):
            # 1. Trim leading/trailing whitespace & non-printable unicode
            cleaned_df[col] = cleaned_df[col].astype(str).str.strip()
            cleaned_df[col] = cleaned_df[col].str.replace(r"[\x00-\x1F\x7F-\x9F]", "", regex=True)

            # 2. Standardize string NULL placeholders
            mask = cleaned_df[col].str.lower().isin(NULL_STRINGS)
            cleaned_df.loc[mask, col] = None

    return cleaned_df
